version: '3.7'

services:
  front:
    build:
      context: ./frontend
    container_name: front
    ports:
      - 80:80
    command: nginx -g daemon off;

  back:
    build: ./backend
    container_name: backend
    ports:
      - 8000:8000
    command: uwsgi --wsgi-file bandcruit/wsgi.py --http 0.0.0.0:8000
    env_file:
      - ./.env
    volumes:
      - ./backend/:/srv/

  db:
    image: mysql:8.0.22
    container_name: mysql.db
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - ./.env

#   nginx:
#     container_name: nginx.prod
#     build: ./nginx
#     volumes:
#       - static_volume:/home/app/web/staticfiles
#     ports:
#       - 80:80
#     depends_on:
#       - front

volumes:
  mysql_data:
#   static_volume: