version: '3.7'

services:
  front:
    # TODO: fix image
    # image: titieiti/metaband:1.1
    build: ./frontend
    container_name: front
    ports:
      - 443:443
    command: nginx -g "daemon off;"
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
    restart: always

  back:
    build: ./backend
    container_name: backend
    ports:
      - 8000:8000
    command: uwsgi --wsgi-file bandcruit/wsgi.py --http 0.0.0.0:8000
    env_file:
      - ./.env
    volumes:
      - ./backend/:/srv/
    restart: always

