version: '3.7'

services:
  front:
    image: titieiti/metaband:1.0
    container_name: front
    ports:
      - 80:80
    command: nginx -g "daemon off;"
    restart: always

  back:
    build: ./backend
    container_name: backend
    ports:
      - 8000:8000
    command: uwsgi --wsgi-file bandcruit/wsgi.py --http 0.0.0.0:8000
    env_file:
      - ./.env
    volumes:
      - ./backend/:/srv/
    restart: always

  db:
    image: mysql:8.0.22
    container_name: mysql.db
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - ./.env
    restart: always

volumes:
  mysql_data: