version: '3.7'

services:
  front:
    # TODO: fix image
    image: chooi221/colabo-mvp-web-front:1.2
    platform: linux/amd64
    # build: ./frontend
    container_name: front
    ports:
      - 443:443
    command: nginx -g "daemon off;"
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
    restart: always

  back:
    build: ./backend
    container_name: backend
    ports:
      - 8000:8000
    command: uwsgi --wsgi-file bandcruit/wsgi.py --http 0.0.0.0:8000
    volumes:
      - ./backend/:/srv/
    restart: always

