# Generated by Django 3.2.6 on 2022-11-15 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20221114_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfollowing',
            old_name='user',
            new_name='user_from',
        ),
        migrations.RenameField(
            model_name='userfollowing',
            old_name='following_user',
            new_name='user_to',
        ),
        migrations.AlterUniqueTogether(
            name='userfollowing',
            unique_together=set(),
        ),
    ]
