# Generated by Django 3.2.6 on 2022-11-15 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20221115_0349'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userfollowing',
            constraint=models.UniqueConstraint(fields=('user_from_id', 'user_to_id'), name='unique_following'),
        ),
    ]
