# Generated by Django 3.2.16 on 2022-11-30 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_userfollowing_unique_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='marketing_agreement',
            field=models.BooleanField(db_column='marketing_agreement', default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='privacy_agreement',
            field=models.BooleanField(db_column='privacy_agreement', default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tos_agreement',
            field=models.BooleanField(db_column='tos_agreement', default=False),
        ),
    ]
