# Generated by Django 3.2.6 on 2022-11-02 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('band', '0007_combinationlog_addr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covertag',
            name='name',
            field=models.CharField(db_column='name', max_length=30, unique=True),
        ),
        migrations.CreateModel(
            name='SongComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(db_column='comment')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='band_songcomment_likes', to=settings.AUTH_USER_MODEL)),
                ('parent_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='band.songcomment')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='band.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'SongComment',
            },
        ),
        migrations.CreateModel(
            name='CoverComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(db_column='comment')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='band.cover')),
                ('likes', models.ManyToManyField(blank=True, related_name='band_covercomment_likes', to=settings.AUTH_USER_MODEL)),
                ('parent_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='band.covercomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'CoverComment',
            },
        ),
        migrations.CreateModel(
            name='CombinationComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(db_column='comment')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('combination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='band.combination')),
                ('likes', models.ManyToManyField(blank=True, related_name='band_combinationcomment_likes', to=settings.AUTH_USER_MODEL)),
                ('parent_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='band.combinationcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'CombinationComment',
            },
        ),
    ]
