# Generated by Django 3.2.6 on 2022-11-02 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0008_auto_20221102_0645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='combinationcomment',
            old_name='comment',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='covercomment',
            old_name='comment',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='songcomment',
            old_name='comment',
            new_name='content',
        ),
    ]
