# Generated by Django 3.2.6 on 2022-11-02 10:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('band', '0009_auto_20221102_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combinationcomment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='band_combinationcomment_Likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='covercomment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='band_covercomment_Likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='songcomment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='band_songcomment_Likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
