# Generated by Django 3.2.6 on 2022-11-03 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('band', '0010_auto_20221102_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combinationcomment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='band_combinationcomment_reply', to='band.combinationcomment'),
        ),
        migrations.AlterField(
            model_name='combinationcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='band_combinationcomment_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='covercomment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='band_covercomment_reply', to='band.covercomment'),
        ),
        migrations.AlterField(
            model_name='covercomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='band_covercomment_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='songcomment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='band_songcomment_reply', to='band.songcomment'),
        ),
        migrations.AlterField(
            model_name='songcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='band_songcomment_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
