# Generated by Django 3.2.6 on 2022-11-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0013_auto_20221103_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cover',
            name='category',
            field=models.CharField(db_column='category', max_length=30),
        ),
    ]
