# Generated by Django 3.2.6 on 2022-11-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0015_auto_20221103_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='Category',
        ),
        migrations.AddField(
            model_name='song',
            name='category',
            field=models.CharField(db_column='category', default='pop', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cover',
            name='category',
            field=models.CharField(db_column='category', default='pop', max_length=30),
            preserve_default=False,
        ),
    ]
