# Generated by Django 3.2.6 on 2022-11-14 11:54

import band.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0016_auto_20221103_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cover',
            name='audio',
            field=models.FileField(editable=False, upload_to=band.models.cover_audio_path),
        ),
    ]
